import { Command } from 'commander';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import { getCaseById, getEvidence } from '../db/index.js';
import { analyze } from '../services/aiService.js';
import { ok, fail, info, section, box, dim } from '../utils/display.js';
import { config } from '../utils/config.js';

export const reportCmd = new Command('report');
reportCmd.description('Generate investigation reports — IC3 complaint, summary, evidence package');

// ── generate ──────────────────────────────────────────────────────────────────
reportCmd
  .command('generate <caseId>')
  .description('Generate full IC3-formatted investigation report')
  .option('-o, --output <path>', 'Output directory', config.casesDir)
  .option('--type <type>', 'Report type (ic3|summary|evidence)', 'ic3')
  .action(async (caseId, opts) => {
    const c = getCaseById(caseId.toUpperCase());
    if (!c) { fail(`Case not found: ${caseId}`); return; }

    const evidence = getEvidence(caseId.toUpperCase());
    section(`GENERATING REPORT — ${caseId} (${opts.type.toUpperCase()})`);

    const ora = (await import('ora')).default;
    const spinner = ora('AI generating report...').start();

    const evidenceSummary = evidence.map((e, i) =>
      `${i + 1}. [${e.type.toUpperCase()}] ${e.description || 'No description'} — ${e.added_at.split(' ')[0]}`
    ).join('\n');

    let prompt;

    if (opts.type === 'ic3') {
      prompt = `Generate a complete IC3 Internet Crime Complaint Center report for this fraud case.

CASE INFORMATION:
Case ID: ${c.case_id}
Title: ${c.title}
Type: ${c.type}
Status: ${c.status}
Victim: ${c.victim || 'Not identified'}
Suspect: ${c.suspect || 'Unknown'}
Description: ${c.description || 'N/A'}
Date Opened: ${c.created_at.split(' ')[0]}
Evidence Count: ${evidence.length}

EVIDENCE LOG:
${evidenceSummary || 'No evidence logged'}

Generate a professional IC3 complaint report with these sections:
1. INCIDENT SUMMARY — Type of crime, date range, brief narrative
2. VICTIM INFORMATION — What was provided / what should be filled in
3. SUSPECT INFORMATION — All known details about perpetrator
4. FINANCIAL LOSSES — Total reported amounts and methods
5. NARRATIVE — Full chronological account of the fraud
6. DIGITAL EVIDENCE — Wallets, emails, URLs, accounts involved
7. SUBMISSION GUIDANCE — Which IC3 category to select, additional agencies to notify (FBI, FTC, EFCC, Europol)
8. CASE NOTES — Investigator findings and recommendations

Be specific. Use all case data provided.`;
    } else if (opts.type === 'summary') {
      prompt = `Write a concise 1-page executive summary for this investigation case.

Case: ${c.title}
Type: ${c.type}
Victim: ${c.victim || 'Unknown'}
Suspect: ${c.suspect || 'Unknown'}
Description: ${c.description || 'N/A'}
Evidence: ${evidence.length} items
${evidenceSummary ? `\nEvidence:\n${evidenceSummary}` : ''}

Include: Key findings, financial impact, current status, immediate recommended actions.`;
    } else {
      prompt = `Create an evidence package index for this investigation.

Case: ${c.case_id} — ${c.title}
Evidence Items: ${evidence.length}
${evidenceSummary}

Organize the evidence, identify the strongest items, note gaps, and recommend what additional evidence to seek.`;
    }

    let reportText;
    try {
      reportText = await analyze(prompt, 3000);
      spinner.stop();
    } catch (err) {
      spinner.fail('Report generation failed');
      fail(err.message);
      return;
    }

    // Write to file
    const outDir = opts.output;
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 16);
    const fileName = `${c.case_id}-${opts.type}-${timestamp}.txt`;
    const filePath = resolve(outDir, fileName);

    const fullReport =
      `${'='.repeat(70)}\n` +
      `MIA INVESTIGATION REPORT\n` +
      `Case: ${c.case_id} | Type: ${opts.type.toUpperCase()} | Generated: ${new Date().toISOString()}\n` +
      `${'='.repeat(70)}\n\n` +
      reportText +
      `\n\n${'='.repeat(70)}\n` +
      `Generated by Mia — SafeNestT / RZ Core\n` +
      `For lawful investigation and victim protection purposes only.\n` +
      `${'='.repeat(70)}\n`;

    writeFileSync(filePath, fullReport, 'utf-8');

    ok(`Report saved: ${filePath}`);
    section('REPORT PREVIEW');
    box(reportText.slice(0, 800) + (reportText.length > 800 ? '\n\n[... truncated — see full file ...]' : ''));
    dim(`\n  Full report: ${filePath}`);
  });

// ── list ──────────────────────────────────────────────────────────────────────
reportCmd
  .command('list')
  .description('List saved report files')
  .action(async () => {
    const { readdirSync } = await import('fs');
    section('SAVED REPORTS');

    let files;
    try {
      files = readdirSync(config.casesDir).filter(f => f.endsWith('.txt'));
    } catch {
      info(`No reports yet. Run: mia report generate <caseId>`);
      return;
    }

    if (!files.length) { info('No report files found'); return; }

    files.forEach((f, i) => {
      console.log(`  ${i + 1}. ${f}`);
    });
    dim(`\n  Directory: ${config.casesDir}`);
  });
